[package]
name = "latexfogel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
tectonic = "0.14.1"
tectonic_bridge_core = "0.4.0"
tectonic_bundles = "0.3.1"
tectonic_engine_xetex = "0.4.3"
tempfile = "3.8.0"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
reqwest = { version = "0.11.20" }
tokio = { version = "1.32.0", features = ["full"] }
poise = "0.5.6"
image = "0.24.7"
